eva.mongo.uri=mongodb://mongo:27017/admin
eva.mongo.accessioning-database=eva_accession_sharded

spring.datasource.url=jdbc:postgresql://postgres:5432/evapro
spring.datasource.username=eva_user
spring.datasource.password=eva_password
