# Database configuration for local Kubernetes testing
spring.datasource.url=jdbc:postgresql://postgres:5432/evapro
spring.datasource.username=eva_user
spring.datasource.password=eva_password

# MongoDB configuration for local Kubernetes testing
eva.mongo.uri=mongodb://mongo:27017/admin
eva.mongo.accessioning-database=eva_accession_sharded
